# Makefile.dep created Sat Jul 26 03:12:43 PDT 2014
listmap.o: listmap.tcc listmap.h xless.h xpair.h listmap.tcc trace.h
trace.o: trace.cpp trace.h
util.o: util.tcc
util.o: util.cpp util.h trace.h util.tcc
main.o: main.cpp listmap.h xless.h xpair.h listmap.tcc trace.h util.h \
 util.tcc
